#!/bin/bash

source ../../scripts/colors.sh

APP_ENV="development"

cecho "---> Loading environment settings" $BLUE
source config/"$APP_ENV"/env.sh

cecho "---> Starting application in $APP_ENV" $BLUE

DDP_DEFAULT_CONNECTION_URL="http://localhost:3333" METEOR_SETTINGS=$METEOR_SETTINGS  meteor --port $PORT
